#pragma once

using namespace std;

enum ErrorCode
{
	ALL_IS_OK,
	CANT_OPEN_INPUT_FILE,
	CANT_OPEN_OUTPUT_FILE,
	EMPTY_FILE,
	INCORRECT_INPUT_DATA_IN_FILE,
	WRONG_SIZE,
	THE_NUMBER_OF_DOMINO_MORE_20,
	THE_NUMBER_OF_DOMINO_LESS_2
};

int const MAX_QUANTITY_DOMINO = 20;
int const MIN_QUANTITY_DOMINO = 2;
